import { Scene, ItemIndex } from './types';

export const SCENES: Scene[] = [
  { name: '泰摩高地-地穴', label: '地穴', name_en: 'The Pit', label_en: 'Pit' },
  { name: '遗忘高塔', label: '女伯爵', name_en: 'Tower', label_en: 'Countess' },
  { name: '地下墓穴', label: '安姐', name_en: 'Catacombs', label_en: 'Andariel' },
  { name: '哞哞农场', label: '牛场', name_en: 'Moo Moo Farm', label_en: 'Cows' },
  { name: '古代通道', label: '古代水道', name_en: 'Ancient Tunnels', label_en: 'AT' },
  { name: '塔拉夏古墓', label: '塔拉夏', name_en: 'Tal Rasha Tombs', label_en: 'Tal Rasha' },
  { name: '崔凡克', label: '3C', name_en: 'Travincal', label_en: 'Council' },
  { name: '憎恨囚牢', label: '劳模', name_en: 'Durance of Hate', label_en: 'Mephisto' },
  { name: '混沌避难所', label: '超市', name_en: 'Chaos Sanctuary', label_en: 'Chaos' },
  { name: '尼拉塞克', label: 'KP', name_en: 'Halls of Vaught', label_en: 'Pindleskin' },
  { name: '世界之石', label: 'KB', name_en: 'Worldstone Keep', label_en: 'Baal' },
  { name: '恐怖地带', label: 'TZ', name_en: 'Terror Zone', label_en: 'TZ' }
];

export const ITEMS: ItemIndex[] = [
  { _id: 'r01', name: 'El Rune', name_zh: '艾尔 (1#)', rarity: '4', color: '#ffa500' },
  { _id: 'r02', name: 'Eld Rune', name_zh: '艾德 (2#)', rarity: '4', color: '#ffa500' },
  { _id: 'r03', name: 'Tir Rune', name_zh: '特尔 (3#)', rarity: '4', color: '#ffa500' },
  { _id: 'r04', name: 'Nef Rune', name_zh: '那夫 (4#)', rarity: '4', color: '#ffa500' },
  { _id: 'r05', name: 'Eth Rune', name_zh: '艾斯 (5#)', rarity: '4', color: '#ffa500' },
  { _id: 'r06', name: 'Ith Rune', name_zh: '伊司 (6#)', rarity: '4', color: '#ffa500' },
  { _id: 'r07', name: 'Tal Rune', name_zh: '塔尔 (7#)', rarity: '4', color: '#ffa500' },
  { _id: 'r08', name: 'Ral Rune', name_zh: '拉尔 (8#)', rarity: '4', color: '#ffa500' },
  { _id: 'r09', name: 'Ort Rune', name_zh: '欧特 (9#)', rarity: '4', color: '#ffa500' },
  { _id: 'r10', name: 'Thul Rune', name_zh: '图尔 (10#)', rarity: '4', color: '#ffa500' },
  { _id: 'r11', name: 'Amn Rune', name_zh: '安姆 (11#)', rarity: '4', color: '#ffa500' },
  { _id: 'r12', name: 'Sol Rune', name_zh: '索尔 (12#)', rarity: '4', color: '#ffa500' },
  { _id: 'r13', name: 'Shael Rune', name_zh: '沙伊 (13#)', rarity: '4', color: '#ffa500' },
  { _id: 'r14', name: 'Dol Rune', name_zh: '多尔 (14#)', rarity: '4', color: '#ffa500' },
  { _id: 'r15', name: 'Hel Rune', name_zh: '海尔 (15#)', rarity: '4', color: '#ffa500' },
  { _id: 'r16', name: 'Io Rune', name_zh: '埃欧 (16#)', rarity: '4', color: '#ffa500' },
  { _id: 'r17', name: 'Lum Rune', name_zh: '卢姆 (17#)', rarity: '4', color: '#ffa500' },
  { _id: 'r18', name: 'Ko Rune', name_zh: '科 (18#)', rarity: '4', color: '#ffa500' },
  { _id: 'r19', name: 'Fal Rune', name_zh: '法尔 (19#)', rarity: '4', color: '#ffa500' },
  { _id: 'r20', name: 'Lem Rune', name_zh: '莱姆 (20#)', rarity: '4', color: '#ffa500' },
  { _id: 'r21', name: 'Pul Rune', name_zh: '普尔 (21#)', rarity: '4', color: '#ffa500' },
  { _id: 'r22', name: 'Um Rune', name_zh: '乌姆 (22#)', rarity: '4', color: '#ffa500' },
  { _id: 'r23', name: 'Mal Rune', name_zh: '马尔 (23#)', rarity: '4', color: '#ffa500' },
  { _id: 'r24', name: 'Ist Rune', name_zh: '伊斯特 (24#)', rarity: '4', color: '#ffa500' },
  { _id: 'r25', name: 'Gul Rune', name_zh: '古尔 (25#)', rarity: '4', color: '#ffa500' },
  { _id: 'r26', name: 'Vex Rune', name_zh: '伐克斯 (26#)', rarity: '4', color: '#ffa500' },
  { _id: 'r27', name: 'Ohm Rune', name_zh: '欧姆 (27#)', rarity: '4', color: '#ffa500' },
  { _id: 'r28', name: 'Lo Rune', name_zh: '罗 (28#)', rarity: '4', color: '#ffa500' },
  { _id: 'r29', name: 'Sur Rune', name_zh: '瑟 (29#)', rarity: '4', color: '#ffa500' },
  { _id: 'r30', name: 'Ber Rune', name_zh: '贝 (30#)', rarity: '4', color: '#ffa500' },
  { _id: 'r31', name: 'Jah Rune', name_zh: '乔 (31#)', rarity: '4', color: '#ffa500' },
  { _id: 'r32', name: 'Cham Rune', name_zh: '查姆 (32#)', rarity: '4', color: '#ffa500' },
  { _id: 'r33', name: 'Zod Rune', name_zh: '萨德 (33#)', rarity: '4', color: '#ffa500' },

  {
    _id: '21',
    name: "The General's Tan Do Li Ga",
    name_zh: '将军的短连枷',
    rarity: '1',
    color: '#d4af37'
  },
  { _id: '48', name: "Dimoak's Hew", name_zh: '迪马克的劈斧', rarity: '1', color: '#d4af37' },
  { _id: '76', name: 'Howltusk', name_zh: '怒号长牙', rarity: '1', color: '#d4af37' },
  { _id: '70', name: 'Doomslinger', name_zh: '末日投手', rarity: '1', color: '#d4af37' },
  { _id: '62', name: "Rogue's Bow", name_zh: '游猎之弓', rarity: '1', color: '#d4af37' },
  { _id: '81', name: 'The Centurion', name_zh: '百夫长', rarity: '1', color: '#d4af37' },
  { _id: '35', name: "Kinemil's Awl", name_zh: '金麦尔的锥子', rarity: '1', color: '#d4af37' },
  { _id: '64', name: 'Wizendraw', name_zh: '凋零劲弦', rarity: '1', color: '#d4af37' },
  { _id: '15', name: 'Knell Striker', name_zh: '丧钟敲击者', rarity: '1', color: '#d4af37' },
  { _id: '4', name: 'Rakescar', name_zh: '钯肉斧', rarity: '1', color: '#d4af37' },
  { _id: '52', name: 'Woestave', name_zh: '降灾长戟', rarity: '1', color: '#d4af37' },
  { _id: '16', name: 'Rusthandle', name_zh: '腐锈权柄', rarity: '1', color: '#d4af37' },
  { _id: '28', name: 'Gleamscythe', name_zh: '寒光镰刀', rarity: '1', color: '#d4af37' },
  { _id: '67', name: 'Leadcrow', name_zh: '铅鸦', rarity: '1', color: '#d4af37' },
  { _id: '41', name: 'The Jade Tan Do', name_zh: '玉尖刀', rarity: '1', color: '#d4af37' },
  { _id: '53', name: 'The Grim Reaper', name_zh: '恐怖收割者', rarity: '1', color: '#d4af37' },
  { _id: '31', name: 'Hellplague', name_zh: '地狱瘟疫', rarity: '1', color: '#d4af37' },
  { _id: '3', name: 'Skull Splitter', name_zh: '凿颅者', rarity: '1', color: '#d4af37' },
  { _id: '11', name: 'Maelstrom', name_zh: '漩涡之力', rarity: '1', color: '#d4af37' },
  { _id: '93', name: 'Heavenly Garb', name_zh: '天界圣衣', rarity: '1', color: '#d4af37' },
  { _id: '90', name: 'Rattlecage', name_zh: '作响之笼', rarity: '1', color: '#d4af37' },
  { _id: '6', name: 'Goreshovel', name_zh: '铲肉斧', rarity: '1', color: '#d4af37' },
  { _id: '87', name: 'Iceblink', name_zh: '闪耀冰晶', rarity: '1', color: '#d4af37' },
  { _id: '0', name: 'The Gnasher', name_zh: '血肉撕咬', rarity: '1', color: '#d4af37' },
  { _id: '78', name: 'The Face of Horror', name_zh: '恐惧面容', rarity: '1', color: '#d4af37' },
  { _id: '63', name: 'Stormstrike', name_zh: '风暴之击', rarity: '1', color: '#d4af37' },
  { _id: '75', name: 'Wormskull', name_zh: '蛆虫头骨', rarity: '1', color: '#d4af37' },
  {
    _id: '30',
    name: "Griswold's Edge",
    name_zh: '格里斯沃尔德之锋',
    rarity: '1',
    color: '#d4af37'
  },
  { _id: '13', name: "Ume's Lament", name_zh: '婴灵的哀歌', rarity: '1', color: '#d4af37' },
  { _id: '19', name: 'Crushflange', name_zh: '四叶破甲锤', rarity: '1', color: '#d4af37' },
  { _id: '38', name: 'The Patriarch', name_zh: '大族长', rarity: '1', color: '#d4af37' },
  { _id: '40', name: 'The Diggler', name_zh: '迪格勒', rarity: '1', color: '#d4af37' },
  { _id: '80', name: "Blinkbat's Form", name_zh: '火蝠之影', rarity: '1', color: '#d4af37' },
  { _id: '23', name: 'Bonesnap', name_zh: '碎骨', rarity: '1', color: '#d4af37' },
  { _id: '9', name: 'Humongous', name_zh: '巨无霸', rarity: '1', color: '#d4af37' },
  { _id: '68', name: 'Ichorsting', name_zh: '灵液之刺', rarity: '1', color: '#d4af37' },
  { _id: '83', name: 'Darkglow', name_zh: '黑暗幽光', rarity: '1', color: '#d4af37' },
  { _id: '18', name: 'Stoutnail', name_zh: '坚硬钉爪', rarity: '1', color: '#d4af37' },
  { _id: '44', name: 'Razortine', name_zh: '剃刀尖齿', rarity: '1', color: '#d4af37' },
  { _id: '34', name: 'Soulflay', name_zh: '剥魂者', rarity: '1', color: '#d4af37' },
  { _id: '74', name: 'Duskdeep', name_zh: '黄昏薄暮', rarity: '1', color: '#d4af37' },
  { _id: '39', name: 'Gull', name_zh: '海鸥', rarity: '1', color: '#d4af37' },
  { _id: '14', name: 'Felloak', name_zh: '凶猛橡木', rarity: '1', color: '#d4af37' },
  { _id: '42', name: 'Spectral Shard', name_zh: '彩虹碎片', rarity: '1', color: '#d4af37' },
  { _id: '57', name: 'The Salamander', name_zh: '沙罗曼', rarity: '1', color: '#d4af37' },
  { _id: '50', name: 'Soul Harvest', name_zh: '收魂者', rarity: '1', color: '#d4af37' },
  { _id: '65', name: 'Hellclap', name_zh: '地狱飞啸', rarity: '1', color: '#d4af37' },
  { _id: '82', name: 'Twitchthroe', name_zh: '抽搐阵痛', rarity: '1', color: '#d4af37' },
  { _id: '37', name: 'Ripsaw', name_zh: '碎肉锯', rarity: '1', color: '#d4af37' },
  { _id: '86', name: 'Venom Ward', name_zh: '毒液禁区', rarity: '1', color: '#d4af37' },
  { _id: '85', name: 'Sparking Mail', name_zh: '电光锁甲', rarity: '1', color: '#d4af37' },
  { _id: '1', name: 'Deathspade', name_zh: '死亡黑桃', rarity: '1', color: '#d4af37' },
  { _id: '71', name: "Biggin's Bonnet", name_zh: '幼童软帽', rarity: '1', color: '#d4af37' },
  { _id: '46', name: 'Lance of Yaggai', name_zh: '亚盖长枪', rarity: '1', color: '#d4af37' },
  { _id: '51', name: 'The Battlebranch', name_zh: '突围者', rarity: '1', color: '#d4af37' },
  { _id: '91', name: 'Goldskin', name_zh: '黄金之肤', rarity: '1', color: '#d4af37' },
  { _id: '43', name: 'The Dragon Chang', name_zh: '龙枪', rarity: '1', color: '#d4af37' },
  { _id: '66', name: 'Blastbark', name_zh: '爆裂喧嚣', rarity: '1', color: '#d4af37' },
  { _id: '79', name: 'Greyform', name_zh: '灰影', rarity: '1', color: '#d4af37' },
  { _id: '77', name: 'Undead Crown', name_zh: '不死王冠', rarity: '1', color: '#d4af37' },
  { _id: '61', name: 'Raven Claw', name_zh: '血鸦之爪', rarity: '1', color: '#d4af37' },
  { _id: '17', name: 'Stormeye', name_zh: '风暴之眼', rarity: '1', color: '#d4af37' },
  { _id: '32', name: "Culwen's Point", name_zh: '库文之刺', rarity: '1', color: '#d4af37' },
  { _id: '36', name: 'Blacktongue', name_zh: '黑舌', rarity: '1', color: '#d4af37' },
  { _id: '72', name: 'Tarnhelm', name_zh: '塔恩之盔', rarity: '1', color: '#d4af37' },
  { _id: '47', name: 'The Tannr Gorerod', name_zh: '皮匠的血刺枪', rarity: '1', color: '#d4af37' },
  { _id: '20', name: 'Bloodrise', name_zh: '血色飞星', rarity: '1', color: '#d4af37' },
  { _id: '5', name: 'Axe of Fechmar', name_zh: '费屈玛之斧', rarity: '1', color: '#d4af37' },
  { _id: '58', name: 'The Iron Jang Bong', name_zh: '铁长棍', rarity: '1', color: '#d4af37' },
  { _id: '60', name: 'Witherstring', name_zh: '凋零之击', rarity: '1', color: '#d4af37' },
  { _id: '69', name: 'Hellcast', name_zh: '狱火投手', rarity: '1', color: '#d4af37' },
  { _id: '55', name: 'Serpent Lord', name_zh: '海蛇之王', rarity: '1', color: '#d4af37' },
  { _id: '22', name: 'Ironstone', name_zh: '铁石', rarity: '1', color: '#d4af37' },
  {
    _id: '56',
    name: 'Spire of Lazarus',
    name_zh: '拉扎鲁斯的螺旋杖',
    rarity: '1',
    color: '#d4af37'
  },
  { _id: '45', name: 'Bloodthief', name_zh: '血贼', rarity: '1', color: '#d4af37' },
  { _id: '33', name: 'Shadowfang', name_zh: '暗影之牙', rarity: '1', color: '#d4af37' },
  { _id: '26', name: 'Blood Crescent', name_zh: '血色新月', rarity: '1', color: '#d4af37' },
  { _id: '54', name: 'Bane Ash', name_zh: '祸根之灰', rarity: '1', color: '#d4af37' },
  { _id: '24', name: 'Steeldriver', name_zh: '钢榔头', rarity: '1', color: '#d4af37' },
  { _id: '92', name: 'Silks of the Victor', name_zh: '胜者的丝绸', rarity: '1', color: '#d4af37' },
  { _id: '25', name: "Rixot's Keen", name_zh: '瑞克撒特的挽歌', rarity: '1', color: '#d4af37' },
  { _id: '2', name: 'Bladebone', name_zh: '刃骨', rarity: '1', color: '#d4af37' },
  { _id: '27', name: 'Skewer of Krintiz', name_zh: '克林茨的肉叉', rarity: '1', color: '#d4af37' },
  { _id: '84', name: 'Hawkmail', name_zh: '雄鹰甲', rarity: '1', color: '#d4af37' },
  { _id: '73', name: 'Coif of Glory', name_zh: '荣光锁帽', rarity: '1', color: '#d4af37' },
  { _id: '49', name: 'Steelgoad', name_zh: '钢刺棒', rarity: '1', color: '#d4af37' },
  { _id: '10', name: 'Torch of Iro', name_zh: '伊洛的火炬', rarity: '1', color: '#d4af37' },
  { _id: '8', name: 'Brainhew', name_zh: '劈颅者', rarity: '1', color: '#d4af37' },
  { _id: '7', name: 'The Chieftain', name_zh: '酋长', rarity: '1', color: '#d4af37' },
  { _id: '59', name: 'Pluckeye', name_zh: '剜眼', rarity: '1', color: '#d4af37' },
  { _id: '108', name: 'Gorefoot', name_zh: '践血', rarity: '1', color: '#d4af37' },
  { _id: '12', name: 'Gravenspine', name_zh: '脊骨雕塑', rarity: '1', color: '#d4af37' },
  { _id: '114', name: 'Nightsmoke', name_zh: '夜烟', rarity: '1', color: '#d4af37' },
  { _id: '98', name: 'Swordback Hold', name_zh: '剑背之架', rarity: '1', color: '#d4af37' },
  { _id: '99', name: 'Steelclash', name_zh: '响钢', rarity: '1', color: '#d4af37' },
  {
    _id: '141',
    name: 'Arm of King Leoric',
    name_zh: '李奥瑞克的臂骨',
    rarity: '1',
    color: '#d4af37'
  },
  { _id: '95', name: 'Umbral Disk', name_zh: '太阳黑轮', rarity: '1', color: '#d4af37' },
  { _id: '101', name: 'The Ward', name_zh: '御敌', rarity: '1', color: '#d4af37' },
  { _id: '144', name: "Zakarum's Hand", name_zh: '萨卡兰姆之手', rarity: '1', color: '#d4af37' },
  { _id: '131', name: 'Islestrike', name_zh: '海岛之击', rarity: '1', color: '#d4af37' },
  { _id: '145', name: 'The Fetid Sprinkler', name_zh: '恶臭喷杖', rarity: '1', color: '#d4af37' },
  { _id: '103', name: 'Bloodfist', name_zh: '染血拳套', rarity: '1', color: '#d4af37' },
  { _id: '132', name: "Pompeii's Wrath", name_zh: '庞贝之怒', rarity: '1', color: '#d4af37' },
  { _id: '140', name: 'Cairn Shard', name_zh: '石冢碎片', rarity: '1', color: '#d4af37' },
  { _id: '121', name: 'Manald Heal', name_zh: '马纳德的治疗', rarity: '1.0', color: '#d4af37' },
  { _id: '118', name: 'The Eye of Etlich', name_zh: '艾利奇之眼', rarity: '1', color: '#d4af37' },
  { _id: '110', name: 'Goblin Toe', name_zh: '哥布林之趾', rarity: '1', color: '#d4af37' },
  { _id: '136', name: 'Stormrider', name_zh: '御雷者', rarity: '1', color: '#d4af37' },
  { _id: '112', name: 'Lenymo', name_zh: '雷尼摩', rarity: '1', color: '#d4af37' },
  { _id: '96', name: 'Stormguild', name_zh: '风暴行会', rarity: '1', color: '#d4af37' },
  { _id: '143', name: 'Dark Clan Crusher', name_zh: '暗族粉碎者', rarity: '1', color: '#d4af37' },
  { _id: '146', name: 'Hand of Blessed Light', name_zh: '圣光之手', rarity: '1', color: '#d4af37' },
  { _id: '94', name: 'Pelta Lunata', name_zh: '新月小盾', rarity: '1', color: '#d4af37' },
  { _id: '88', name: 'Boneflesh', name_zh: '骨肉分离', rarity: '1', color: '#d4af37' },
  { _id: '104', name: 'Chance Guards', name_zh: '吉运守护', rarity: '1', color: '#d4af37' },
  { _id: '100', name: 'Bverrit Keep', name_zh: '贝弗提的壁垒', rarity: '1', color: '#d4af37' },
  { _id: '111', name: 'Tearhaunch', name_zh: '刺股靴', rarity: '1', color: '#d4af37' },
  { _id: '97', name: 'Wall of the Eyeless', name_zh: '无眼之墙', rarity: '1', color: '#d4af37' },
  { _id: '117', name: 'Nokozan Relic', name_zh: '诺克兰的遗物', rarity: '1', color: '#d4af37' },
  { _id: '107', name: 'Hotspur', name_zh: '热刺靴', rarity: '1', color: '#d4af37' },
  { _id: '161', name: 'The Atlantean', name_zh: '亚特兰蒂斯剑', rarity: '1', color: '#d4af37' },
  { _id: '106', name: 'Frostburn', name_zh: '霜灼', rarity: '1', color: '#d4af37' },
  { _id: '165', name: 'Cloudcrack', name_zh: '裂云剑', rarity: '1', color: '#d4af37' },
  { _id: '109', name: 'Treads of Cthon', name_zh: '克索恩的征途', rarity: '1', color: '#d4af37' },
  { _id: '166', name: 'Todesfaelle Flamme', name_zh: '索命之焰', rarity: '1', color: '#d4af37' },
  { _id: '142', name: 'Blackhand Key', name_zh: '黑手钥匙', rarity: '1', color: '#d4af37' },
  { _id: '167', name: 'Swordguard', name_zh: '卫剑', rarity: '1', color: '#d4af37' },
  { _id: '168', name: 'Spineripper', name_zh: '裂脊者', rarity: '1', color: '#d4af37' },
  { _id: '139', name: 'Suicide Branch', name_zh: '自戕树杈', rarity: '1', color: '#d4af37' },
  { _id: '160', name: 'Plague Bearer', name_zh: '瘟疫散播者', rarity: '1', color: '#d4af37' },
  { _id: '129', name: 'Coldkill', name_zh: '冰殛', rarity: '1', color: '#d4af37' },
  { _id: '164', name: 'The Vile Husk', name_zh: '邪祟之牙', rarity: '1', color: '#d4af37' },
  { _id: '154', name: 'Bloodletter', name_zh: '放血者', rarity: '1', color: '#d4af37' },
  { _id: '130', name: "Butcher's Pupil", name_zh: '屠夫之瞳', rarity: '1', color: '#d4af37' },
  { _id: '122', name: 'The Stone of Jordan', name_zh: '乔丹之石', rarity: '1', color: '#d4af37' },
  { _id: '151', name: 'Earthshaker', name_zh: '震地者', rarity: '1', color: '#d4af37' },
  { _id: '162', name: 'Crainte Vomir', name_zh: '恐惧喷吐', rarity: '1', color: '#d4af37' },
  { _id: '158', name: "Ginther's Rift", name_zh: '金瑟的破空之痕', rarity: '1', color: '#d4af37' },
  { _id: '155', name: 'Coldsteal Eye', name_zh: '冷窃之眼', rarity: '1', color: '#d4af37' },
  { _id: '115', name: 'Goldwrap', name_zh: '金织带', rarity: '1', color: '#d4af37' },
  { _id: '149', name: 'Moonfall', name_zh: '月陨', rarity: '1', color: '#d4af37' },
  { _id: '137', name: 'Boneslayer Blade', name_zh: '碎骨者之刃', rarity: '1', color: '#d4af37' },
  { _id: '157', name: 'Blade of Ali Baba', name_zh: '阿里巴巴之刃', rarity: '1', color: '#d4af37' },
  { _id: '133', name: 'Guardian Naga', name_zh: '蛇神守护者', rarity: '1', color: '#d4af37' },
  { _id: '148', name: 'Sureshrill Frost', name_zh: '神河之霜', rarity: '1', color: '#d4af37' },
  { _id: '159', name: 'Headstriker', name_zh: '斩首者', rarity: '1', color: '#d4af37' },
  { _id: '153', name: 'The Gavel of Pain', name_zh: '苦痛木槌', rarity: '1', color: '#d4af37' },
  { _id: '147', name: 'Fleshrender', name_zh: '血肉撕裂者', rarity: '1', color: '#d4af37' },
  { _id: '150', name: "Baezil's Vortex", name_zh: '贝希尔的漩涡', rarity: '1', color: '#d4af37' },
  { _id: '120', name: 'Nagelring', name_zh: '纳格尔之戒', rarity: '1.0', color: '#d4af37' },
  { _id: '169', name: 'Heart Carver', name_zh: '剜心者', rarity: '1', color: '#d4af37' },
  { _id: '156', name: 'Hexfire', name_zh: '妖术之火', rarity: '1', color: '#d4af37' },
  { _id: '152', name: 'Bloodtree Stump', name_zh: '龙血木桩', rarity: '1', color: '#d4af37' },
  { _id: '105', name: 'Magefist', name_zh: '法师之拳', rarity: '1', color: '#d4af37' },
  { _id: '89', name: 'Rockfleece', name_zh: '石中毛', rarity: '1', color: '#d4af37' },
  { _id: '134', name: "Warlord's Trust", name_zh: '战争领主的信赖', rarity: '1', color: '#d4af37' },
  { _id: '163', name: 'Bing Sz Wang', name_zh: '冰之王', rarity: '1', color: '#d4af37' },
  { _id: '102', name: 'The Hand of Broc', name_zh: '布洛克之手', rarity: '1', color: '#d4af37' },
  { _id: '138', name: 'The Minotaur', name_zh: '牛魔斧', rarity: '1', color: '#d4af37' },
  { _id: '116', name: 'Bladebuckle', name_zh: '刀刃腰扣', rarity: '1', color: '#d4af37' },
  { _id: '170', name: "Blackbog's Sharp", name_zh: '黑沼之锋', rarity: '1', color: '#d4af37' },
  {
    _id: '119',
    name: 'The Mahim-Oak Curio',
    name_zh: '马哈姆橡木珍品',
    rarity: '1',
    color: '#d4af37'
  },
  { _id: '135', name: 'Spellsteel', name_zh: '魔咒之钢', rarity: '1', color: '#d4af37' },
  { _id: '113', name: 'Snakecord', name_zh: '蛇皮索', rarity: '1', color: '#d4af37' },
  { _id: '171', name: 'Stormspike', name_zh: '风暴匕刺', rarity: '1', color: '#d4af37' },
  { _id: '173', name: 'Kelpie Snare', name_zh: '水妖捕叉', rarity: '1', color: '#d4af37' },
  { _id: '176', name: 'Spire of Honor', name_zh: '荣耀之巅', rarity: '1', color: '#d4af37' },
  { _id: '174', name: 'Soulfeast Tine', name_zh: '噬魂叉', rarity: '1', color: '#d4af37' },
  { _id: '172', name: 'The Impaler', name_zh: '穿刺者', rarity: '1', color: '#d4af37' },
  { _id: '178', name: 'Blackleach Blade', name_zh: '暗蚀之刃', rarity: '1', color: '#d4af37' },
  { _id: '192', name: 'Witchwild String', name_zh: '狂法劲弦', rarity: '1', color: '#d4af37' },
  { _id: '175', name: 'Hone Sundan', name_zh: '骨寸断', rarity: '1', color: '#d4af37' },
  { _id: '181', name: 'Husoldal Evo', name_zh: '皮肉吞噬者', rarity: '1', color: '#d4af37' },
  { _id: '184', name: 'Ribcracker', name_zh: '肋骨粉碎者', rarity: '1', color: '#d4af37' },
  { _id: '177', name: 'The Meat Scraper', name_zh: '刮肉长戟', rarity: '1', color: '#d4af37' },
  { _id: '185', name: 'Chromatic Ire', name_zh: '多彩之怒', rarity: '1', color: '#d4af37' },
  { _id: '179', name: "Athena's Wrath", name_zh: '雅典娜之怒', rarity: '1', color: '#d4af37' },
  { _id: '191', name: 'Endlesshail', name_zh: '无尽冰雹', rarity: '1', color: '#d4af37' },
  { _id: '189', name: 'Riphook', name_zh: '撕裂之钩', rarity: '1', color: '#d4af37' },
  { _id: '183', name: 'Razorswitch', name_zh: '剃刀飞旋', rarity: '1', color: '#d4af37' },
  { _id: '186', name: 'Warpspear', name_zh: '扭曲之矛', rarity: '1', color: '#d4af37' },
  { _id: '187', name: 'Skull Collector', name_zh: '骷髅收集者', rarity: '1', color: '#d4af37' },
  { _id: '188', name: 'Skystrike', name_zh: '天击', rarity: '1', color: '#d4af37' },
  { _id: '180', name: 'Pierre Tombale Couant', name_zh: '墓石长戟', rarity: '1', color: '#d4af37' },
  { _id: '193', name: 'Cliffkiller', name_zh: '峭壁杀手', rarity: '1', color: '#d4af37' },
  {
    _id: '182',
    name: "Grim's Burning Dead",
    name_zh: '格里姆的烈焰亡灵',
    rarity: '1',
    color: '#d4af37'
  },
  { _id: '194', name: 'Magewrath', name_zh: '法师之怒', rarity: '1', color: '#d4af37' },
  { _id: '204', name: 'Darksight Helm', name_zh: '暗视头盔', rarity: '1', color: '#d4af37' },
  { _id: '201', name: 'Peasant Crown', name_zh: '农夫兜帽', rarity: '1', color: '#d4af37' },
  { _id: '190', name: 'Kuko Shakaku', name_zh: '赤焰之击', rarity: '1', color: '#d4af37' },
  { _id: '224', name: 'Visceratuant', name_zh: '刨肠', rarity: '1', color: '#d4af37' },
  { _id: '251', name: "Arkaine's Valor", name_zh: '阿凯尼的荣耀', rarity: '1', color: '#d4af37' },
  { _id: '239', name: 'Silkweave', name_zh: '丝织靴', rarity: '1', color: '#d4af37' },
  { _id: '205', name: 'Valkyrie Wing', name_zh: '女武神之翼', rarity: '1', color: '#d4af37' },
  { _id: '256', name: "Baranar's Star", name_zh: '巴拉纳之星', rarity: '1', color: '#d4af37' },
  { _id: '207', name: "Blackhorn's Face", name_zh: '黑牛角面甲', rarity: '1', color: '#d4af37' },
  { _id: '218', name: 'Guardian Angel', name_zh: '守护天使', rarity: '1', color: '#d4af37' },
  { _id: '199', name: 'Demon Machine', name_zh: '恶魔机弩', rarity: '1', color: '#d4af37' },
  { _id: '211', name: 'Skin of Flayed One', name_zh: '剥皮魔之皮', rarity: '1', color: '#d4af37' },
  { _id: '259', name: 'Lightsabre', name_zh: '光之军刀', rarity: '1', color: '#d4af37' },
  { _id: '198', name: 'Buriza-Do Kyanon', name_zh: '暴雪重炮', rarity: '1', color: '#d4af37' },
  { _id: '208', name: 'Vampire Gaze', name_zh: '吸血鬼的凝视', rarity: '1', color: '#d4af37' },
  { _id: '226', name: 'Stormchaser', name_zh: '风暴追逐者', rarity: '1', color: '#d4af37' },
  { _id: '196', name: 'Langer Briser', name_zh: '千步碎击', rarity: '1', color: '#d4af37' },
  { _id: '237', name: 'Infernostride', name_zh: '地狱阔步', rarity: '1', color: '#d4af37' },
  {
    _id: '223',
    name: "Que-Hegan's Wisdom",
    name_zh: '魁黑刚的智慧',
    rarity: '1',
    color: '#d4af37'
  },
  { _id: '206', name: 'Crown of Thieves', name_zh: '盗贼皇冠', rarity: '1', color: '#d4af37' },
  {
    _id: '229',
    name: "Radament's Sphere",
    name_zh: '罗达门特的领地',
    rarity: '1',
    color: '#d4af37'
  },
  { _id: '209', name: 'The Spirit Shroud', name_zh: '覆灵尸衣', rarity: '1', color: '#d4af37' },
  { _id: '219', name: 'Toothrow', name_zh: '排齿', rarity: '1', color: '#d4af37' },
  { _id: '212', name: 'Iron Pelt', name_zh: '铁皮', rarity: '1', color: '#d4af37' },
  {
    _id: '210',
    name: 'Skin of the Vipermagi',
    name_zh: '蝮蛇法妖之皮',
    rarity: '1',
    color: '#d4af37'
  },
  { _id: '230', name: 'Lidless Wall', name_zh: '警戒之墙', rarity: '1', color: '#d4af37' },
  {
    _id: '228',
    name: "Gerke's Sanctuary",
    name_zh: '基尔克的避难地',
    rarity: '1',
    color: '#d4af37'
  },
  { _id: '222', name: 'Corpsemourn', name_zh: '遗体哀悼', rarity: '1', color: '#d4af37' },
  { _id: '261', name: 'The Grandfather', name_zh: '祖父', rarity: '1', color: '#d4af37' },
  {
    _id: '255',
    name: "Messerschmidt's Reaver",
    name_zh: '梅塞施密特的劫掠者',
    rarity: '1',
    color: '#d4af37'
  },
  { _id: '233', name: 'Gravepalm', name_zh: '盗墓手套', rarity: '1', color: '#d4af37' },
  { _id: '246', name: "Thundergod's Vigor", name_zh: '雷神之力', rarity: '1', color: '#d4af37' },
  { _id: '234', name: 'Ghoulhide', name_zh: '食尸鬼皮', rarity: '1', color: '#d4af37' },
  { _id: '215', name: 'Shaftstop', name_zh: '摧锋甲', rarity: '1', color: '#d4af37' },
  { _id: '217', name: "Skullder's Ire", name_zh: '诗寇蒂的愤怒', rarity: '1', color: '#00ff00' },
  { _id: '214', name: 'Crow Caw', name_zh: '鸦鸣', rarity: '1', color: '#d4af37' },
  { _id: '249', name: 'Veil of Steel', name_zh: '钢铁面纱', rarity: '1', color: '#d4af37' },
  { _id: '227', name: "Tiamat's Rebuke", name_zh: '魔龙的斥责', rarity: '1', color: '#d4af37' },
  { _id: '197', name: 'Pus Spitter', name_zh: '吐脓毒弩', rarity: '1', color: '#d4af37' },
  { _id: '244', name: "Gloom's Trap", name_zh: '阴影陷阱', rarity: '1', color: '#d4af37' },
  { _id: '203', name: 'Stealskull', name_zh: '偷取颅盔', rarity: '1', color: '#d4af37' },
  { _id: '216', name: "Duriel's Shell", name_zh: '督瑞尔之壳', rarity: '1', color: '#d4af37' },
  { _id: '242', name: 'String of Ears', name_zh: '缠腰耳串', rarity: '1', color: '#d4af37' },
  { _id: '235', name: 'Lava Gout', name_zh: '熔岩痛击', rarity: '1', color: '#d4af37' },
  { _id: '248', name: 'Harlequin Crest', name_zh: '谐角之冠', rarity: '1', color: '#d4af37' },
  { _id: '257', name: "Schaefer's Hammer", name_zh: '舍费尔之锤', rarity: '1', color: '#d4af37' },
  { _id: '241', name: 'Gore Rider', name_zh: '血骑士', rarity: '1', color: '#d4af37' },
  { _id: '195', name: 'Goldstrike Arch', name_zh: '金击之弧', rarity: '1', color: '#d4af37' },
  { _id: '238', name: 'Waterwalk', name_zh: '水上飘', rarity: '1', color: '#d4af37' },
  { _id: '243', name: 'Razortail', name_zh: '剃刀之尾', rarity: '1', color: '#d4af37' },
  { _id: '252', name: 'Blackoak Shield', name_zh: '黑橡树盾', rarity: '1', color: '#d4af37' },
  { _id: '202', name: 'Rockstopper', name_zh: '磐石头盔', rarity: '1', color: '#d4af37' },
  { _id: '262', name: 'Wizardspike', name_zh: '巫师之刺', rarity: '1', color: '#d4af37' },
  { _id: '260', name: 'Doombringer', name_zh: '末日使者', rarity: '1', color: '#d4af37' },
  {
    _id: '225',
    name: "Moser's Blessed Circle",
    name_zh: '莫泽的祝福圆盾',
    rarity: '1',
    color: '#d4af37'
  },
  { _id: '220', name: "Atma's Wail", name_zh: '阿特玛的哭喊', rarity: '1', color: '#d4af37' },
  { _id: '245', name: 'Snowclash', name_zh: '冰雪之击', rarity: '1', color: '#d4af37' },
  { _id: '240', name: 'War Traveler', name_zh: '战争旅者', rarity: '1', color: '#d4af37' },
  { _id: '232', name: 'Venom Grip', name_zh: '剧毒之握', rarity: '1', color: '#d4af37' },
  { _id: '258', name: 'The Cranium Basher', name_zh: '碎颅', rarity: '1', color: '#d4af37' },
  { _id: '253', name: 'Stormshield', name_zh: '暴风之盾', rarity: '1', color: '#d4af37' },
  { _id: '254', name: 'Hellslayer', name_zh: '地狱屠戮者', rarity: '1', color: '#d4af37' },
  { _id: '213', name: 'Spirit Forge', name_zh: '灵魂熔炉', rarity: '1', color: '#d4af37' },
  { _id: '221', name: 'Black Hades', name_zh: '黑色冥王', rarity: '1', color: '#d4af37' },
  { _id: '236', name: 'Hellmouth', name_zh: '地狱之口', rarity: '1', color: '#d4af37' },
  { _id: '264', name: 'Stormspire', name_zh: '暴风螺旋', rarity: '1', color: '#d4af37' },
  { _id: '269', name: "The Cat's Eye", name_zh: '猫眼', rarity: '1', color: '#d4af37' },
  {
    _id: '250',
    name: "The Gladiator's Bane",
    name_zh: '角斗士之祸',
    rarity: '1',
    color: '#d4af37'
  },
  {
    _id: '268',
    name: "Bul-Kathos' Wedding Band",
    name_zh: '布尔凯索的婚戒',
    rarity: '1',
    color: '#d4af37'
  },
  { _id: '265', name: 'Eaglehorn', name_zh: '鹰之号角', rarity: '1', color: '#d4af37' },
  { _id: '271', name: 'Crescent Moon', name_zh: '新月', rarity: '1', color: '#d4af37' },
  { _id: '231', name: 'Lance Guard', name_zh: '长枪卫士', rarity: '1', color: '#d4af37' },
  { _id: '270', name: 'The Rising Sun', name_zh: '旭日', rarity: '1', color: '#d4af37' },
  { _id: '274', name: 'Dwarf Star', name_zh: '矮人之星', rarity: '1', color: '#d4af37' },
  { _id: '266', name: 'Windforce', name_zh: '风之力', rarity: '1', color: '#d4af37' },
  { _id: '277', name: "Saracen's Chance", name_zh: '撒拉森的胜机', rarity: '1', color: '#d4af37' },
  { _id: '276', name: "Highlord's Wrath", name_zh: '至高王之怒', rarity: '1', color: '#d4af37' },
  {
    _id: '272',
    name: "Mara's Kaleidoscope",
    name_zh: '玛拉的万花筒',
    rarity: '1',
    color: '#d4af37'
  },
  { _id: '273', name: "Atma's Scarab", name_zh: '阿特玛的圣甲虫', rarity: '1', color: '#d4af37' },
  { _id: '275', name: 'Raven Frost', name_zh: '乌鸦之霜', rarity: '1', color: '#d4af37' },
  { _id: '280', name: 'Homunculus', name_zh: '魔胎', rarity: '1', color: '#d4af37' },
  { _id: '279', name: "Arreat's Face", name_zh: '亚瑞特之貌', rarity: '1', color: '#d4af37' },
  { _id: '281', name: "Titan's Revenge", name_zh: '泰坦的复仇', rarity: '1', color: '#d4af37' },
  { _id: '290', name: 'Djinn Slayer', name_zh: '邪灵斩', rarity: '1', color: '#d4af37' },
  { _id: '296', name: 'Demon Limb', name_zh: '恶魔断肢', rarity: '1', color: '#d4af37' },
  {
    _id: '286',
    name: "Bartuc's Cut-Throat",
    name_zh: '巴图克的割喉爪',
    rarity: '1',
    color: '#d4af37'
  },
  { _id: '292', name: 'Warshrike', name_zh: '战争伯劳鸟', rarity: '1', color: '#d4af37' },
  { _id: '283', name: "Lycander's Flank", name_zh: '莱姗德的侧击', rarity: '1', color: '#d4af37' },
  { _id: '291', name: 'Deathbit', name_zh: '死亡之吻', rarity: '1', color: '#d4af37' },
  { _id: '310', name: "Cerebus' Bite", name_zh: '冥犬的撕咬', rarity: '1', color: '#d4af37' },
  {
    _id: '285',
    name: 'Herald of Zakarum',
    name_zh: '萨卡兰姆的使者',
    rarity: '1',
    color: '#d4af37'
  },
  { _id: '284', name: 'The Oculus', name_zh: '海妖之瞳', rarity: '1', color: '#d4af37' },
  { _id: '307', name: 'Stone Crusher', name_zh: '碎石者', rarity: '1', color: '#d4af37' },
  { _id: '289', name: 'Bloodmoon', name_zh: '血月', rarity: '1', color: '#d4af37' },
  { _id: '300', name: "Nature's Peace", name_zh: '大自然的安宁', rarity: '1', color: '#d4af37' },
  { _id: '312', name: 'Soul Drainer', name_zh: '吸魂者', rarity: '1', color: '#d4af37' },
  { _id: '309', name: 'Shadow Dancer', name_zh: '影舞者', rarity: '1', color: '#d4af37' },
  { _id: '287', name: "Jalal's Mane", name_zh: '狼王之鬃', rarity: '1', color: '#d4af37' },
  { _id: '282', name: "Lycander's Aim", name_zh: '莱姗德的远击', rarity: '1', color: '#d4af37' },
  { _id: '301', name: 'Azurewrath', name_zh: '碧蓝怒火', rarity: '1', color: '#d4af37' },
  { _id: '288', name: 'The Scalper', name_zh: '头皮剥离者', rarity: '1', color: '#d4af37' },
  { _id: '297', name: 'Steel Shade', name_zh: '钢罩', rarity: '1', color: '#d4af37' },
  { _id: '308', name: 'Jade Talon', name_zh: '碧玉爪', rarity: '1', color: '#d4af37' },
  { _id: '302', name: "Seraph's Hymn", name_zh: '炽天使的圣歌', rarity: '1', color: '#d4af37' },
  { _id: '299', name: "Death's Web", name_zh: '死亡之网', rarity: '1', color: '#d4af37' },
  { _id: '311', name: "Tyrael's Might", name_zh: '泰瑞尔的力量', rarity: '1', color: '#d4af37' },
  { _id: '304', name: 'Fleshripper', name_zh: '血肉割裂者', rarity: '1', color: '#d4af37' },
  { _id: '313', name: 'Rune Master', name_zh: '符文大师', rarity: '1', color: '#d4af37' },
  { _id: '298', name: 'Tomb Reaver', name_zh: '墓穴劫掠者', rarity: '1', color: '#d4af37' },
  { _id: '294', name: "Razor's Edge", name_zh: '剃刀之锋', rarity: '1', color: '#d4af37' },
  {
    _id: '306',
    name: "Horizon's Tornado",
    name_zh: '地平线的龙卷风',
    rarity: '1',
    color: '#d4af37'
  },
  { _id: '293', name: 'Gut Siphon', name_zh: '碎胆', rarity: '1', color: '#d4af37' },
  { _id: '314', name: 'Death Cleaver', name_zh: '死亡切肉斧', rarity: '1', color: '#d4af37' },
  { _id: '316', name: 'Stoneraven', name_zh: '石鸦', rarity: '1', color: '#d4af37' },
  { _id: '321', name: 'Lacerator', name_zh: '撕裂者', rarity: '1', color: '#d4af37' },
  {
    _id: '315',
    name: "Executioner's Justice",
    name_zh: '行刑者的裁决',
    rarity: '1',
    color: '#d4af37'
  },
  { _id: '319', name: 'Wisp Projector', name_zh: '鬼火投影', rarity: '1', color: '#d4af37' },
  { _id: '317', name: 'Leviathan', name_zh: '利维坦', rarity: '1', color: '#d4af37' },
  { _id: '327', name: 'Spirit Keeper', name_zh: '灵体守护者', rarity: '1', color: '#d4af37' },
  { _id: '324', name: 'Ethereal Edge', name_zh: '无形之锋', rarity: '1', color: '#d4af37' },
  { _id: '323', name: 'Viperfork', name_zh: '蛇信长枪', rarity: '1', color: '#d4af37' },
  { _id: '322', name: "Mang Song's Lesson", name_zh: '宋满的教训', rarity: '1', color: '#d4af37' },
  { _id: '320', name: "Gargoyle's Bite", name_zh: '石像鬼之牙', rarity: '1', color: '#d4af37' },
  { _id: '329', name: 'Alma Negra', name_zh: '黑暗之魂', rarity: '1', color: '#d4af37' },
  { _id: '325', name: "Demonhorn's Edge", name_zh: '恶魔角锋', rarity: '1', color: '#d4af37' },
  { _id: '334', name: 'Shadow Killer', name_zh: '影弑', rarity: '1', color: '#d4af37' },
  {
    _id: '332',
    name: "Blood Raven's Charge",
    name_zh: '血鸦的冲锋',
    rarity: '1',
    color: '#d4af37'
  },
  { _id: '338', name: 'Thunderstroke', name_zh: '雷击', rarity: '1', color: '#d4af37' },
  { _id: '331', name: 'Widowmaker', name_zh: '寡妇制造', rarity: '1', color: '#d4af37' },
  { _id: '343', name: "Nightwing's Veil", name_zh: '夜翼面纱', rarity: '1', color: '#d4af37' },
  { _id: '326', name: "The Reaper's Toll", name_zh: '死神的丧钟', rarity: '1', color: '#d4af37' },
  { _id: '340', name: "Demon's Arch", name_zh: '恶魔扑击', rarity: '1', color: '#d4af37' },
  { _id: '333', name: 'Ghostflame', name_zh: '魂焰', rarity: '1', color: '#d4af37' },
  { _id: '337', name: 'Windhammer', name_zh: '风锤', rarity: '1', color: '#d4af37' },
  { _id: '336', name: "Griffon's Eye", name_zh: '狮鹫之眼', rarity: '1', color: '#d4af37' },
  { _id: '344', name: 'Crown of Ages', name_zh: '年纪之冠', rarity: '1', color: '#d4af37' },
  { _id: '342', name: 'Steel Pillar', name_zh: '钢铁支柱', rarity: '1', color: '#d4af37' },
  { _id: '330', name: 'Darkforce Spawn', name_zh: '魔力肇生', rarity: '1', color: '#d4af37' },
  { _id: '335', name: 'Gimmershred', name_zh: '寒铁飞刃', rarity: '1', color: '#d4af37' },
  { _id: '328', name: 'Hellrack', name_zh: '地狱刑器', rarity: '1', color: '#d4af37' },
  { _id: '348', name: 'Steel Carapace', name_zh: '钢铁甲壳', rarity: '1', color: '#d4af37' },
  { _id: '341', name: 'Boneflame', name_zh: '骨焰', rarity: '1', color: '#d4af37' },
  { _id: '350', name: 'Ravenlore', name_zh: '乌鸦的智慧', rarity: '1', color: '#d4af37' },
  { _id: '347', name: 'Dragonscale', name_zh: '龙鳞', rarity: '1', color: '#d4af37' },
  { _id: '351', name: 'Boneshade', name_zh: '白骨阴魂', rarity: '1', color: '#d4af37' },
  { _id: '349', name: "Medusa's Gaze", name_zh: '美杜莎的凝视', rarity: '1', color: '#d4af37' },
  { _id: '353', name: 'Flamebellow', name_zh: '怒焰咆哮', rarity: '1', color: '#d4af37' },
  { _id: '355', name: 'Wolfhowl', name_zh: '狼嚎', rarity: '1', color: '#d4af37' },
  { _id: '357', name: "Kira's Guardian", name_zh: '奇拉的守护', rarity: '1', color: '#d4af37' },
  {
    _id: '361',
    name: "Halaberd's Reign",
    name_zh: '死亡女神的统治',
    rarity: '1',
    color: '#d4af37'
  },
  { _id: '356', name: 'Spirit Ward', name_zh: '灵体守护', rarity: '1', color: '#d4af37' },
  {
    _id: '345',
    name: "Andariel's Visage",
    name_zh: '安达莉尔的仪容',
    rarity: '1',
    color: '#d4af37'
  },
  { _id: '354', name: "Death's Fathom", name_zh: '死亡深度', rarity: '1', color: '#d4af37' },
  { _id: '366', name: "Templar's Might", name_zh: '圣殿骑士之力', rarity: '1.0', color: '#d4af37' },
  { _id: '363', name: 'Spike Thorn', name_zh: '尖刺荆棘', rarity: '1.0', color: '#d4af37' },
  { _id: '358', name: "Ormus' Robes", name_zh: '奥玛斯的法袍', rarity: '1.0', color: '#d4af37' },
  { _id: '364', name: "Dracul's Grasp", name_zh: '德古拉之握', rarity: '1.0', color: '#d4af37' },
  { _id: '369', name: 'Sandstorm Trek', name_zh: '沙暴之旅', rarity: '1.0', color: '#d4af37' },
  { _id: '360', name: 'Stormlash', name_zh: '风暴之鞭', rarity: '1.0', color: '#d4af37' },
  { _id: '359', name: "Gheed's Fortune", name_zh: '基德的好运', rarity: '1.0', color: '#d4af37' },
  { _id: '370', name: 'Marrowwalk', name_zh: '骨髓行走', rarity: '1.0', color: '#d4af37' },
  { _id: '371', name: "Heaven's Light", name_zh: '天堂之光', rarity: '1.0', color: '#d4af37' },
  { _id: '365', name: 'Frostwind', name_zh: '冰霜之风', rarity: '1.0', color: '#d4af37' },
  {
    _id: '367',
    name: "Eschuta's Temper",
    name_zh: '艾丝屈塔的脾气',
    rarity: '1.0',
    color: '#d4af37'
  },
  {
    _id: '368',
    name: "Firelizard's Talons",
    name_zh: '火蜥蜴之爪',
    rarity: '1.0',
    color: '#d4af37'
  },
  {
    _id: '376',
    name: "Verdungo's Hearty Cord",
    name_zh: '行刑者的绞首绳',
    rarity: '1.0',
    color: '#d4af37'
  },
  {
    _id: '374',
    name: "Nosferatu's Coil",
    name_zh: '吸血圣王之圈',
    rarity: '1.0',
    color: '#d4af37'
  },
  { _id: '382', name: "Arioc's Needle", name_zh: '艾里欧克之针', rarity: '1.0', color: '#d4af37' },
  { _id: '373', name: 'Arachnid Mesh', name_zh: '蜘蛛网纹', rarity: '1.0', color: '#d4af37' },
  { _id: '381', name: 'Annihilus', name_zh: '毁灭', rarity: '1.0', color: '#d4af37' },
  {
    _id: '380',
    name: "Astreon's Iron Ward",
    name_zh: '阿斯特隆的陨铁杖',
    rarity: '1.0',
    color: '#d4af37'
  },
  { _id: '378', name: 'Carrion Wind', name_zh: '腐肉之风', rarity: '1.0', color: '#d4af37' },
  { _id: '375', name: 'Metalgrid', name_zh: '金属网格', rarity: '1.0', color: '#d4af37' },
  {
    _id: '390',
    name: "Head Hunter's Glory",
    name_zh: '猎头者的荣耀',
    rarity: '1.0',
    color: '#d4af37'
  },
  {
    _id: '384',
    name: "Nord's Tenderizer",
    name_zh: '北方人的碎肉河蟹棒',
    rarity: '1.0',
    color: '#d4af37'
  },
  { _id: '386', name: 'Wraith Flight', name_zh: '怨灵飞行', rarity: '1.0', color: '#d4af37' },
  { _id: '379', name: 'Giant Skull', name_zh: '巨型颅骨', rarity: '1.0', color: '#d4af37' },
  { _id: '383', name: 'Cranebeak', name_zh: '鹤嘴锄', rarity: '1.0', color: '#d4af37' },
  { _id: '385', name: 'Earth Shifter', name_zh: '撼地者', rarity: '1.0', color: '#d4af37' },
  { _id: '388', name: "Ondal's Wisdom", name_zh: '温达的智慧', rarity: '1.0', color: '#d4af37' },
  {
    _id: '392',
    name: 'Rainbow Facet',
    name_zh: '彩虹刻面（死电）',
    rarity: '1.0',
    color: '#d4af37'
  },
  {
    _id: '393',
    name: 'Rainbow Facet',
    name_zh: '彩虹刻面（死冰）',
    rarity: '1.0',
    color: '#d4af37'
  },
  {
    _id: '394',
    name: 'Rainbow Facet',
    name_zh: '彩虹刻面（死火）',
    rarity: '1.0',
    color: '#d4af37'
  },
  { _id: '389', name: 'The Redeemer', name_zh: '救赎者', rarity: '1.0', color: '#d4af37' },
  { _id: '391', name: 'Steelrend', name_zh: '碎钢', rarity: '1.0', color: '#d4af37' },
  {
    _id: '397',
    name: 'Rainbow Facet',
    name_zh: '彩虹刻面（活冰）',
    rarity: '1.0',
    color: '#d4af37'
  },
  { _id: '387', name: 'Bonehew', name_zh: '斩骨', rarity: '1.0', color: '#d4af37' },
  {
    _id: '395',
    name: 'Rainbow Facet',
    name_zh: '彩虹刻面（死毒）',
    rarity: '1.0',
    color: '#d4af37'
  },
  {
    _id: '396',
    name: 'Rainbow Facet',
    name_zh: '彩虹刻面（活电）',
    rarity: '1.0',
    color: '#d4af37'
  },
  {
    _id: '399',
    name: 'Rainbow Facet',
    name_zh: '彩虹刻面（活毒）',
    rarity: '1.0',
    color: '#d4af37'
  },
  { _id: '401', name: 'Cold Rupture', name_zh: '冰寒裂缝', rarity: '1.0', color: '#d4af37' },
  {
    _id: '398',
    name: 'Rainbow Facet',
    name_zh: '彩虹刻面（活火）',
    rarity: '1.0',
    color: '#d4af37'
  },
  { _id: '400', name: 'Hellfire Torch', name_zh: '地狱火炬', rarity: '1.0', color: '#d4af37' },
  { _id: '500', name: "Civerb's Ward", name_zh: '希弗伯的防护', rarity: '2.0', color: '#00ff00' },
  { _id: '402', name: 'Flame Rift', name_zh: '火焰裂隙', rarity: '1.0', color: '#d4af37' },
  {
    _id: '403',
    name: 'Crack of the Heavens',
    name_zh: '天堂裂痕',
    rarity: '1.0',
    color: '#d4af37'
  },
  { _id: '404', name: 'Rotting Fissure', name_zh: '腐臭间隙', rarity: '1.0', color: '#d4af37' },
  { _id: '406', name: 'Black Cleft', name_zh: '漆黑裂口', rarity: '1.0', color: '#d4af37' },
  { _id: '405', name: 'Bone Break', name_zh: '分筋裂骨', rarity: '1.0', color: '#d4af37' },
  { _id: '501', name: "Civerb's Icon", name_zh: '希弗伯的圣像', rarity: '2.0', color: '#00ff00' },
  {
    _id: '503',
    name: "Hsarus' Iron Heel",
    name_zh: '萨鲁斯的铁踵',
    rarity: '2.0',
    color: '#00ff00'
  },
  { _id: '502', name: "Civerb's Cudgel", name_zh: '希弗伯的短棍', rarity: '2.0', color: '#00ff00' },
  {
    _id: '504',
    name: "Hsarus' Iron Fist",
    name_zh: '萨鲁斯的铁拳',
    rarity: '2.0',
    color: '#00ff00'
  },
  {
    _id: '509',
    name: "Iratha's Collar",
    name_zh: '艾蕾萨的护颈圈',
    rarity: '2.0',
    color: '#00ff00'
  },
  {
    _id: '505',
    name: "Hsarus' Iron Stay",
    name_zh: '萨鲁斯的铁固腰',
    rarity: '2.0',
    color: '#00ff00'
  },
  { _id: '506', name: "Cleglaw's Tooth", name_zh: '克雷格劳之牙', rarity: '2.0', color: '#00ff00' },
  { _id: '507', name: "Cleglaw's Claw", name_zh: '克雷格劳之爪', rarity: '2.0', color: '#00ff00' },
  {
    _id: '508',
    name: "Cleglaw's Pincers",
    name_zh: '克雷格劳之钳',
    rarity: '2.0',
    color: '#00ff00'
  },
  { _id: '510', name: "Iratha's Cuff", name_zh: '艾蕾萨的袖手套', rarity: '2.0', color: '#00ff00' },
  { _id: '511', name: "Iratha's Coil", name_zh: '艾蕾萨的铁围盔', rarity: '2.0', color: '#00ff00' },
  {
    _id: '514',
    name: "Isenhart's Parry",
    name_zh: '依森哈特的格挡',
    rarity: '2.0',
    color: '#00ff00'
  },
  {
    _id: '513',
    name: "Isenhart's Lightbrand",
    name_zh: '依森哈特的光之烙印',
    rarity: '2.0',
    color: '#00ff00'
  },
  { _id: '512', name: "Iratha's Cord", name_zh: '艾蕾萨的束带', rarity: '2.0', color: '#00ff00' },
  { _id: '517', name: "Vidala's Barb", name_zh: '维达拉的倒刺', rarity: '2.0', color: '#00ff00' },
  {
    _id: '516',
    name: "Isenhart's Horns",
    name_zh: '依森哈特的号角',
    rarity: '2.0',
    color: '#00ff00'
  },
  {
    _id: '518',
    name: "Vidala's Fetlock",
    name_zh: '维达拉的扣带靴',
    rarity: '2.0',
    color: '#00ff00'
  },
  { _id: '520', name: "Vidala's Snare", name_zh: '维达拉的陷阱', rarity: '2.0', color: '#00ff00' },
  { _id: '519', name: "Vidala's Ambush", name_zh: '维达拉的突袭', rarity: '2.0', color: '#00ff00' },
  {
    _id: '515',
    name: "Isenhart's Case",
    name_zh: '依森哈特的胸胄',
    rarity: '2.0',
    color: '#00ff00'
  },
  {
    _id: '521',
    name: "Milabrega's Orb",
    name_zh: '米拉伯佳的宝球',
    rarity: '2.0',
    color: '#00ff00'
  },
  {
    _id: '522',
    name: "Milabrega's Rod",
    name_zh: '米拉伯佳的权杖',
    rarity: '2.0',
    color: '#00ff00'
  },
  {
    _id: '523',
    name: "Milabrega's Diadem",
    name_zh: '米拉伯佳的冠冕',
    rarity: '2.0',
    color: '#00ff00'
  },
  {
    _id: '524',
    name: "Milabrega's Robe",
    name_zh: '米拉伯佳的袍甲',
    rarity: '2.0',
    color: '#00ff00'
  },
  {
    _id: '530',
    name: "Tancred's Crowbill",
    name_zh: '坦克雷的鸦嘴锄',
    rarity: '2.0',
    color: '#00ff00'
  },
  { _id: '529', name: "Cathan's Seal", name_zh: '卡珊的印章', rarity: '2.0', color: '#00ff00' },
  { _id: '527', name: "Cathan's Visage", name_zh: '卡珊的面甲', rarity: '2.0', color: '#00ff00' },
  { _id: '525', name: "Cathan's Rule", name_zh: '卡珊的统治', rarity: '2.0', color: '#00ff00' },
  { _id: '528', name: "Cathan's Sigil", name_zh: '卡珊的符徽', rarity: '2.0', color: '#00ff00' },
  { _id: '526', name: "Cathan's Mesh", name_zh: '卡珊的札甲', rarity: '2.0', color: '#00ff00' },
  { _id: '531', name: "Tancred's Spine", name_zh: '坦克雷的脊柱', rarity: '2.0', color: '#00ff00' },
  { _id: '533', name: "Tancred's Weird", name_zh: '坦克雷的怪诞', rarity: '2.0', color: '#00ff00' },
  {
    _id: '532',
    name: "Tancred's Hobnails",
    name_zh: '坦克雷的钉头鞋',
    rarity: '2.0',
    color: '#00ff00'
  },
  { _id: '534', name: "Tancred's Skull", name_zh: '坦克雷的头骨', rarity: '2.0', color: '#00ff00' },
  { _id: '540', name: "Sigon's Guard", name_zh: '西刚的守护', rarity: '2.0', color: '#00ff00' },
  { _id: '539', name: "Sigon's Wrap", name_zh: '西刚的腰带', rarity: '2.0', color: '#00ff00' },
  { _id: '535', name: "Sigon's Gage", name_zh: '西刚的挑战', rarity: '2.0', color: '#00ff00' },
  { _id: '538', name: "Sigon's Sabot", name_zh: '西刚的木底鞋', rarity: '2.0', color: '#00ff00' },
  { _id: '536', name: "Sigon's Visor", name_zh: '西刚的面甲', rarity: '2.0', color: '#00ff00' },
  { _id: '537', name: "Sigon's Shelter", name_zh: '西刚的遮蔽', rarity: '2.0', color: '#00ff00' },
  { _id: '543', name: 'Infernal Sign', name_zh: '地狱印记', rarity: '2.0', color: '#00ff00' },
  { _id: '541', name: 'Infernal Cranium', name_zh: '地狱颅骨', rarity: '2.0', color: '#00ff00' },
  { _id: '542', name: 'Infernal Torch', name_zh: '地狱火炬', rarity: '2.0', color: '#00ff00' },
  {
    _id: '544',
    name: "Berserker's Headgear",
    name_zh: '狂战士的头盔',
    rarity: '2.0',
    color: '#00ff00'
  },
  { _id: '550', name: 'Angelic Sickle', name_zh: '天使的镰刀', rarity: '2.0', color: '#00ff00' },
  { _id: '547', name: "Death's Hand", name_zh: '死神之手', rarity: '2.0', color: '#00ff00' },
  { _id: '549', name: "Death's Touch", name_zh: '死神之触', rarity: '2.0', color: '#00ff00' },
  {
    _id: '545',
    name: "Berserker's Hauberk",
    name_zh: '狂战士的锁甲',
    rarity: '2.0',
    color: '#00ff00'
  },
  {
    _id: '546',
    name: "Berserker's Hatchet",
    name_zh: '狂战士的手斧',
    rarity: '2.0',
    color: '#00ff00'
  },
  { _id: '548', name: "Death's Guard", name_zh: '死神之卫', rarity: '2.0', color: '#00ff00' },
  { _id: '551', name: 'Angelic Mantle', name_zh: '天使的披风', rarity: '2.0', color: '#00ff00' },
  { _id: '552', name: 'Angelic Halo', name_zh: '天使的光环', rarity: '2.0', color: '#00ff00' },
  { _id: '553', name: 'Angelic Wings', name_zh: '天使的飞翼', rarity: '2.0', color: '#00ff00' },
  { _id: '554', name: 'Arctic Horn', name_zh: '北极号角', rarity: '2.0', color: '#00ff00' },
  { _id: '556', name: 'Arctic Binding', name_zh: '北极束带', rarity: '2.0', color: '#00ff00' },
  { _id: '557', name: 'Arctic Mitts', name_zh: '北极手套', rarity: '2.0', color: '#00ff00' },
  { _id: '555', name: 'Arctic Furs', name_zh: '北极毛皮', rarity: '2.0', color: '#00ff00' },
  {
    _id: '559',
    name: "Arcanna's Deathwand",
    name_zh: '阿卡娜的死亡之杖',
    rarity: '2.0',
    color: '#00ff00'
  },
  { _id: '560', name: "Arcanna's Head", name_zh: '阿卡娜的头', rarity: '2.0', color: '#00ff00' },
  { _id: '558', name: "Arcanna's Sign", name_zh: '阿卡娜的符号', rarity: '2.0', color: '#00ff00' },
  { _id: '561', name: "Arcanna's Flesh", name_zh: '阿卡娜的血肉', rarity: '2.0', color: '#00ff00' },
  { _id: '563', name: "Natalya's Mark", name_zh: '娜塔亚的标记', rarity: '2.0', color: '#00ff00' },
  { _id: '562', name: "Natalya's Totem", name_zh: '娜塔亚的徽记', rarity: '2.0', color: '#00ff00' },
  {
    _id: '564',
    name: "Natalya's Shadow",
    name_zh: '娜塔亚的阴影',
    rarity: '2.0',
    color: '#00ff00'
  },
  { _id: '565', name: "Natalya's Soul", name_zh: '娜塔亚的灵魂', rarity: '2.0', color: '#00ff00' },
  {
    _id: '567',
    name: "Aldur's Deception",
    name_zh: '艾尔多的欺骗',
    rarity: '2.0',
    color: '#00ff00'
  },
  { _id: '568', name: "Aldur's Rhythm", name_zh: '艾尔多的律动', rarity: '2.0', color: '#00ff00' },
  {
    _id: '566',
    name: "Aldur's Stony Gaze",
    name_zh: '艾尔多的冷酷凝视',
    rarity: '2.0',
    color: '#00ff00'
  },
  { _id: '569', name: "Aldur's Advance", name_zh: '艾尔多的成长', rarity: '2.0', color: '#00ff00' },
  {
    _id: '570',
    name: "Immortal King's Will",
    name_zh: '不朽之王的意志',
    rarity: '2.0',
    color: '#00ff00'
  },
  {
    _id: '571',
    name: "Immortal King's Soul Cage",
    name_zh: '不朽之王的灵魂之笼',
    rarity: '2.0',
    color: '#00ff00'
  },
  {
    _id: '572',
    name: "Immortal King's Detail",
    name_zh: '不朽之王的功业',
    rarity: '2.0',
    color: '#00ff00'
  },
  {
    _id: '574',
    name: "Immortal King's Pillar",
    name_zh: '不朽之王的基石',
    rarity: '2.0',
    color: '#00ff00'
  },
  {
    _id: '573',
    name: "Immortal King's Forge",
    name_zh: '不朽之王的锤炼',
    rarity: '2.0',
    color: '#00ff00'
  },
  {
    _id: '575',
    name: "Immortal King's Stone Crusher",
    name_zh: '不朽之王的碎石锤',
    rarity: '2.0',
    color: '#00ff00'
  },
  {
    _id: '580',
    name: "Tal Rasha's Horadric Crest",
    name_zh: '塔·拉夏的赫拉迪姆之冠',
    rarity: '2.0',
    color: '#00ff00'
  },
  {
    _id: '578',
    name: "Tal Rasha's Lidless Eye",
    name_zh: '塔·拉夏的无睑之眼',
    rarity: '2.0',
    color: '#00ff00'
  },
  {
    _id: '577',
    name: "Tal Rasha's Adjudication",
    name_zh: '塔·拉夏的裁决',
    rarity: '2.0',
    color: '#00ff00'
  },
  {
    _id: '579',
    name: "Tal Rasha's Guardianship",
    name_zh: '塔·拉夏的守护',
    rarity: '2.0',
    color: '#00ff00'
  },
  {
    _id: '576',
    name: "Tal Rasha's Fine-Spun Cloth",
    name_zh: '塔·拉夏的精织带',
    rarity: '2.0',
    color: '#00ff00'
  },
  {
    _id: '582',
    name: "Griswold's Heart",
    name_zh: '格里斯沃尔德的赤诚',
    rarity: '2.0',
    color: '#00ff00'
  },
  {
    _id: '581',
    name: "Griswold's Valor",
    name_zh: '格里斯沃尔德的勇气',
    rarity: '2.0',
    color: '#00ff00'
  },
  {
    _id: '583',
    name: "Griswold's Redemption",
    name_zh: '格里斯沃尔德的救赎',
    rarity: '2.0',
    color: '#00ff00'
  },
  {
    _id: '584',
    name: "Griswold's Honor",
    name_zh: '格里斯沃尔德的荣耀',
    rarity: '2.0',
    color: '#00ff00'
  },
  {
    _id: '588',
    name: "Trang-Oul's Claws",
    name_zh: '塔格奥的利爪',
    rarity: '2.0',
    color: '#00ff00'
  },
  {
    _id: '586',
    name: "Trang-Oul's Scales",
    name_zh: '塔格奥的鳞片',
    rarity: '2.0',
    color: '#00ff00'
  },
  {
    _id: '590',
    name: "M'avina's True Sight",
    name_zh: '艾维娜的真视',
    rarity: '2.0',
    color: '#00ff00'
  },
  {
    _id: '587',
    name: "Trang-Oul's Wing",
    name_zh: '塔格奥的飞翼',
    rarity: '2.0',
    color: '#00ff00'
  },
  {
    _id: '585',
    name: "Trang-Oul's Guise",
    name_zh: '塔格奥的伪装',
    rarity: '2.0',
    color: '#00ff00'
  },
  {
    _id: '589',
    name: "Trang-Oul's Girth",
    name_zh: '塔格奥的肚带',
    rarity: '2.0',
    color: '#00ff00'
  },
  {
    _id: '591',
    name: "M'avina's Embrace",
    name_zh: '艾维娜的拥抱',
    rarity: '2.0',
    color: '#00ff00'
  },
  {
    _id: '594',
    name: "M'avina's Caster",
    name_zh: '艾维娜的施展',
    rarity: '2.0',
    color: '#00ff00'
  },
  { _id: '593', name: "M'avina's Tenet", name_zh: '艾维娜的教义', rarity: '2.0', color: '#00ff00' },
  {
    _id: '592',
    name: "M'avina's Icy Clutch",
    name_zh: '艾维娜的冰握',
    rarity: '2.0',
    color: '#00ff00'
  },
  {
    _id: '600',
    name: "Dangoon's Teaching",
    name_zh: '覃君的教导',
    rarity: '2.0',
    color: '#00ff00'
  },
  { _id: '596', name: 'Laying of Hands', name_zh: '按手礼套', rarity: '2.0', color: '#00ff00' },
  { _id: '595', name: 'Telling of Beads', name_zh: '赐福念珠', rarity: '2.0', color: '#00ff00' },
  { _id: '597', name: 'Rite of Passage', name_zh: '皈依之道', rarity: '2.0', color: '#00ff00' },
  { _id: '599', name: 'Credendum', name_zh: '信念腰带', rarity: '2.0', color: '#00ff00' },
  { _id: '598', name: 'Dark Adherent', name_zh: '隐秘教徒', rarity: '2.0', color: '#00ff00' },
  {
    _id: '602',
    name: "Haemosu's Adamant",
    name_zh: '解慕苏的坚定',
    rarity: '2.0',
    color: '#00ff00'
  },
  { _id: '601', name: "Taebaek's Glory", name_zh: '泰白的荣耀', rarity: '2.0', color: '#00ff00' },
  { _id: '604', name: "Guillaume's Face", name_zh: '威廉的威容', rarity: '2.0', color: '#00ff00' },
  { _id: '603', name: "Ondal's Almighty", name_zh: '温达的全灵', rarity: '2.0', color: '#00ff00' },
  { _id: '609', name: "Hwanin's Refuge", name_zh: '桓因的庇佑', rarity: '2.0', color: '#00ff00' },
  { _id: '606', name: "Magnus' Skin", name_zh: '雄主的皮手套', rarity: '2.0', color: '#00ff00' },
  { _id: '608', name: "Hwanin's Splendor", name_zh: '桓因的壮美', rarity: '2.0', color: '#00ff00' },
  { _id: '607', name: "Whitstan's Guard", name_zh: '威斯顿之御', rarity: '2.0', color: '#00ff00' },
  { _id: '605', name: "Willhelm's Pride", name_zh: '威廉的骄傲', rarity: '2.0', color: '#00ff00' },
  { _id: '610', name: "Hwanin's Blessing", name_zh: '桓因的祝福', rarity: '2.0', color: '#00ff00' },
  { _id: '611', name: "Hwanin's Justice", name_zh: '桓因的圣裁', rarity: '2.0', color: '#00ff00' },
  {
    _id: '612',
    name: "Sazabi's Cobalt Redeemer",
    name_zh: '圣·沙略的济世之剑',
    rarity: '2.0',
    color: '#00ff00'
  },
  {
    _id: '614',
    name: "Sazabi's Mental Sheath",
    name_zh: '圣·沙略的心灵庇护',
    rarity: '2.0',
    color: '#00ff00'
  },
  {
    _id: '613',
    name: "Sazabi's Ghost Liberator",
    name_zh: '圣·沙略的魂灵解救者',
    rarity: '2.0',
    color: '#00ff00'
  },
  { _id: '618', name: "Cow King's Hide", name_zh: '牛魔王之皮', rarity: '2.0', color: '#00ff00' },
  { _id: '617', name: "Cow King's Horns", name_zh: '牛魔王之角', rarity: '2.0', color: '#00ff00' },
  {
    _id: '616',
    name: "Bul-Kathos' Tribal Guardian",
    name_zh: '布尔凯索的部族守护',
    rarity: '2.0',
    color: '#00ff00'
  },
  { _id: '620', name: "Naj's Puzzler", name_zh: '诺吉的解密棒', rarity: '2.0', color: '#00ff00' },
  { _id: '619', name: "Cow King's Hooves", name_zh: '牛魔王之蹄', rarity: '2.0', color: '#00ff00' },
  {
    _id: '615',
    name: "Bul-Kathos' Sacred Charge",
    name_zh: '布尔凯索的神圣职责',
    rarity: '2.0',
    color: '#00ff00'
  },
  {
    _id: '621',
    name: "Naj's Light Plate",
    name_zh: '诺吉的轻铠甲',
    rarity: '2.0',
    color: '#00ff00'
  },
  { _id: '622', name: "Naj's Circlet", name_zh: '诺吉的头环', rarity: '2.0', color: '#00ff00' },
  { _id: '801', name: "Ancients' Pledge", name_zh: '先祖之誓', rarity: '3', color: '#ffa500' },
  { _id: '804', name: 'Beast', name_zh: '野兽', rarity: '3', color: '#ffa500' },
  { _id: '806', name: 'Black', name_zh: '黑色', rarity: '3', color: '#ffa500' },
  { _id: '809', name: 'Bramble', name_zh: '荆棘', rarity: '3', color: '#ffa500' },
  { _id: '813', name: 'Call to Arms', name_zh: '战争召唤', rarity: '3', color: '#ffa500' },
  { _id: '808', name: 'Bone', name_zh: '白骨', rarity: '3', color: '#ffa500' },
  { _id: '810', name: 'Brand', name_zh: '烙印', rarity: '3', color: '#ffa500' },
  { _id: '811', name: 'Breath of the Dying', name_zh: '濒死之息', rarity: '3', color: '#ffa500' },
  { _id: '814', name: 'Chains of Honor', name_zh: '荣耀之链', rarity: '3', color: '#ffa500' },
  { _id: '817', name: 'Crescent Moon', name_zh: '新月', rarity: '3', color: '#ffa500' },
  { _id: '816', name: 'Chaos', name_zh: '混沌', rarity: '3', color: '#ffa500' },
  { _id: '820', name: 'Death', name_zh: '死亡', rarity: '3', color: '#ffa500' },
  { _id: '826', name: 'Doom', name_zh: '厄运', rarity: '3', color: '#ffa500' },
  { _id: '822', name: 'Delirium', name_zh: '迷狂', rarity: '3', color: '#ffa500' },
  { _id: '825', name: 'Destruction', name_zh: '毁灭', rarity: '3', color: '#ffa500' },
  { _id: '830', name: 'Duress', name_zh: '强压', rarity: '3', color: '#ffa500' },
  { _id: '827', name: 'Dragon', name_zh: '巨龙', rarity: '3', color: '#ffa500' },
  { _id: '829', name: 'Dream', name_zh: '梦境', rarity: '3', color: '#ffa500' },
  { _id: '833', name: 'Enigma', name_zh: '谜团', rarity: '3', color: '#ffa500' },
  { _id: '831', name: 'Edge', name_zh: '锐锋', rarity: '3', color: '#ffa500' },
  { _id: '836', name: 'Eternity', name_zh: '永恒', rarity: '3', color: '#ffa500' },
  { _id: '834', name: 'Enlightenment', name_zh: '启迪', rarity: '3', color: '#ffa500' },
  { _id: '837', name: 'Exile', name_zh: '流放', rarity: '3', color: '#ffa500' },
  { _id: '844', name: 'Fury', name_zh: '愤怒', rarity: '3', color: '#ffa500' },
  { _id: '841', name: 'Fortitude', name_zh: '刚毅', rarity: '3', color: '#ffa500' },
  { _id: '839', name: 'Famine', name_zh: '饥荒', rarity: '3', color: '#ffa500' },
  { _id: '840', name: 'Flickering Flame', name_zh: '摇曳的火焰', rarity: '3', color: '#ffa500' },
  { _id: '838', name: 'Faith', name_zh: '信念', rarity: '3', color: '#ffa500' },
  { _id: '849', name: 'Harmony', name_zh: '和谐', rarity: '3', color: '#ffa500' },
  { _id: '848', name: 'Hand of Justice', name_zh: '正义之手', rarity: '3', color: '#ffa500' },
  { _id: '847', name: 'Grief', name_zh: '悔恨', rarity: '3', color: '#ffa500' },
  { _id: '845', name: 'Gloom', name_zh: '阴霾', rarity: '3', color: '#ffa500' },
  { _id: '851', name: 'Heart of the Oak', name_zh: '橡树之心', rarity: '3', color: '#ffa500' },
  { _id: '860', name: 'Infinity', name_zh: '无限', rarity: '3', color: '#ffa500' },
  { _id: '855', name: 'Honor', name_zh: '荣耀', rarity: '3', color: '#ffa500' },
  { _id: '862', name: 'Insight', name_zh: '眼光', rarity: '3', color: '#ffa500' },
  { _id: '854', name: 'Holy Thunder', name_zh: '圣雷', rarity: '3', color: '#ffa500' },
  { _id: '859', name: 'Ice', name_zh: '寒冰', rarity: '3', color: '#ffa500' },
  { _id: '865', name: "King's Grace", name_zh: '王恩', rarity: '3', color: '#ffa500' },
  { _id: '866', name: 'Kingslayer', name_zh: '弑君者', rarity: '3', color: '#ffa500' },
  { _id: '871', name: 'Lawbringer', name_zh: '执法者', rarity: '3', color: '#ffa500' },
  { _id: '869', name: 'Last Wish', name_zh: '临终之愿', rarity: '3', color: '#ffa500' },
  { _id: '872', name: 'Leaf', name_zh: '叶子', rarity: '3', color: '#ffa500' },
  { _id: '875', name: 'Lore', name_zh: '学识', rarity: '3', color: '#ffa500' },
  { _id: '882', name: 'Melody', name_zh: '旋律', rarity: '3', color: '#ffa500' },
  { _id: '881', name: 'Malice', name_zh: '怨恨', rarity: '3', color: '#ffa500' },
  { _id: '874', name: 'Lionheart', name_zh: '狮心', rarity: '3', color: '#ffa500' },
  { _id: '883', name: 'Memory', name_zh: '回忆', rarity: '3', color: '#ffa500' },
  { _id: '891', name: 'Oath', name_zh: '誓言', rarity: '3', color: '#ffa500' },
  { _id: '888', name: 'Nadir', name_zh: '天底', rarity: '3', color: '#ffa500' },
  { _id: '887', name: 'Myth', name_zh: '神话', rarity: '3', color: '#ffa500' },
  { _id: '884', name: 'Mist', name_zh: '迷雾', rarity: '3', color: '#ffa500' },
  { _id: '895', name: 'Passion', name_zh: '热情', rarity: '3', color: '#ffa500' },
  { _id: '897', name: 'Pattern', name_zh: '模式', rarity: '3', color: '#ffa500' },
  { _id: '899', name: 'Voice of Reason', name_zh: '理智之声', rarity: '3', color: '#ffa500' },
  { _id: '892', name: 'Obedience', name_zh: '顺从', rarity: '3', color: '#ffa500' },
  { _id: '894', name: 'Obsession', name_zh: '着魔', rarity: '3', color: '#ffa500' },
  { _id: '898', name: 'Peace', name_zh: '平和', rarity: '3', color: '#ffa500' },
  { _id: '903', name: 'Phoenix', name_zh: '凤凰', rarity: '3', color: '#ffa500' },
  { _id: '910', name: 'Principle', name_zh: '信条', rarity: '3', color: '#ffa500' },
  { _id: '909', name: 'Pride', name_zh: '骄傲', rarity: '3', color: '#ffa500' },
  { _id: '906', name: 'Plague', name_zh: '瘟疫', rarity: '3', color: '#ffa500' },
  { _id: '921', name: 'Rift', name_zh: '裂隙', rarity: '3', color: '#ffa500' },
  { _id: '922', name: 'Sanctuary', name_zh: '庇护', rarity: '3', color: '#ffa500' },
  { _id: '912', name: 'Prudence', name_zh: '谨慎', rarity: '3', color: '#ffa500' },
  { _id: '917', name: 'Rain', name_zh: '暴雨', rarity: '3', color: '#ffa500' },
  { _id: '920', name: 'Rhyme', name_zh: '韵律', rarity: '3', color: '#ffa500' },
  { _id: '916', name: 'Radiance', name_zh: '光辉', rarity: '3', color: '#ffa500' },
  { _id: '931', name: 'Splendor', name_zh: '壮美', rarity: '3', color: '#ffa500' },
  { _id: '926', name: 'Silence', name_zh: '沉默', rarity: '3', color: '#ffa500' },
  { _id: '930', name: 'Spirit', name_zh: '精神', rarity: '3', color: '#ffa500' },
  { _id: '928', name: 'Smoke', name_zh: '烟雾', rarity: '3', color: '#ffa500' },
  { _id: '933', name: 'Stealth', name_zh: '隐秘', rarity: '3', color: '#ffa500' },
  { _id: '948', name: 'Treachery', name_zh: '背叛', rarity: '3', color: '#ffa500' },
  { _id: '937', name: 'Stone', name_zh: '磐石', rarity: '3', color: '#ffa500' },
  { _id: '939', name: 'Strength', name_zh: '力量', rarity: '3', color: '#ffa500' },
  { _id: '951', name: 'Unbending Will', name_zh: '不屈意志', rarity: '3', color: '#ffa500' },
  { _id: '934', name: 'Steel', name_zh: '钢铁', rarity: '3', color: '#ffa500' },
  { _id: '954', name: 'Venom', name_zh: '毒液', rarity: '3', color: '#ffa500' },
  { _id: '963', name: 'Wind', name_zh: '疾风', rarity: '3', color: '#ffa500' },
  { _id: '960', name: 'Wealth', name_zh: '财富', rarity: '3', color: '#ffa500' },
  { _id: '962', name: 'White', name_zh: '白色', rarity: '3', color: '#ffa500' },
  { _id: '971', name: 'Hustle (armor)', name_zh: '匆忙', rarity: '3', color: '#ffa500' },
  { _id: '972', name: 'Hustle (weapon)', name_zh: '匆忙', rarity: '3', color: '#ffa500' },
  { _id: '968', name: 'Wrath', name_zh: '怒火', rarity: '3', color: '#ffa500' },
  { _id: '965', name: 'Wisdom', name_zh: '智慧', rarity: '3', color: '#ffa500' },
  { _id: '970', name: 'Zephyr', name_zh: '和风', rarity: '3', color: '#ffa500' },
  { _id: '973', name: 'Mosaic', name_zh: '马赛克', rarity: '3', color: '#ffa500' },
  { _id: '976', name: 'Temper', name_zh: '暴躁', rarity: '3', color: '#ffa500' },
  { _id: '975', name: 'Ground', name_zh: '基础', rarity: '3', color: '#ffa500' },
  { _id: '977', name: 'Hearth', name_zh: '灶火', rarity: '3', color: '#ffa500' },
  { _id: '974', name: 'Metamorphosis', name_zh: '变形', rarity: '3', color: '#ffa500' },
  { _id: '978', name: 'Cure', name_zh: '治疗', rarity: '3', color: '#ffa500' },
  { _id: '979', name: 'Bulwark', name_zh: '堡垒', rarity: '3', color: '#ffa500' },
  { _id: '650', name: "Sander's Paragon", name_zh: '山德的崇拜', rarity: '2.0', color: '#00ff00' },
  {
    _id: '651',
    name: "Sander's Superstition",
    name_zh: '山德的迷信',
    rarity: '2.0',
    color: '#00ff00'
  },
  { _id: '652', name: "Sander's Taboo", name_zh: '山德的禁忌', rarity: '2.0', color: '#00ff00' },
  { _id: '653', name: "Sander's Riprap", name_zh: '山德的石碓', rarity: '2.0', color: '#00ff00' }
];
